version: '3.9'
services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
    - ./src:/var/www
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    build: ./docker/mysql
    volumes:
    - ./docker/mysql/data:/var/lib/mysql
    ports:
    - 3306:3306